import z from "zod";

export const ErrorCode = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

    NOT_FOUND: "NOT_FOUND",

    VALIDATION_ERROR: "VALIDATION_ERROR",

    UNAUTHORIZED: "UNAUTHORIZED",

    FORBIDDEN: "FORBIDDEN",

    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

    CONFLICT: "CONFLICT",

    RATE_LIMITED: "RATE_LIMITED",

    DEPLOYMENT_NOT_FOUND: "DEPLOYMENT_NOT_FOUND",

    DEPLOYMENT_ALREADY_EXISTS: "DEPLOYMENT_ALREADY_EXISTS",

    BUILD_FAILED: "BUILD_FAILED",

    BUILD_NOT_FOUND: "BUILD_NOT_FOUND",

    IMAGE_BUILD_FAILED: "IMAGE_BUILD_FAILED",

    IMAGE_PUSH_FAILED: "IMAGE_PUSH_FAILED",

    CONTAINER_NOT_FOUND: "CONTAINER_NOT_FOUND",

    CONTAINER_START_FAILED: "CONTAINER_START_FAILED",

    CONTAINER_STOP_FAILED: "CONTAINER_STOP_FAILED",

    SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",

    HEALTH_CHECK_FAILED: "HEALTH_CHECK_FAILED",

    RECONCILIATION_FAILED: "RECONCILIATION_FAILED",
} as const;

export const ErrorCodeSchema = z.enum(ErrorCode);

