services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yusra

    ports:
      - "5432:5432"

  redis:
    image: redis:8

    ports:
      - "6379:6379"